services:
  node:
    build: ./.docker/node
    image: js-helper-node
    container_name: js-helper-node
    volumes:
      - ./:/app
    working_dir: /app
    user: 1000:1000
    tty: true
    restart: always
networks:
  default:
    name: js-helper-default
